### ISSUE TITLE
about the project code wrong

### ISSUE THREAD

**Issue by Afleve** [Visual-AI/SPTNet#1]
Thank for your code.
But I found there're some wrong.
`from project_utils.general_utils
from methods.vpt.utils import cosine_lr`
I found general_utils in util,but couldn't cosine_lr

**Comment by whj363636** [comment]
Hi @Onenormler,

Thanks for your interest. The inconsistency you point out caused by refactoring has been fixed now.

**Comment by qingsonghu08** [comment]
NameError: name 'unfreeze' is not defined
`from util.general_utils import freeze, unfreeze`
But I found there is no freeze and unfreeze in general_utils

**Comment by whj363636** [comment]
Hi @qingsonghu08,

Thanks for pointing that out. Already updated it!
