### ISSUE TITLE
Out of memory problem

### ISSUE THREAD

**Issue by RunDevil-Run** [Visual-AI/SPTNet#12]
Hello， I‘ve tried to run the training code， and I have succeded loading the pretrained simgcd weights, but when the code run to 
https://github.com/Visual-AI/SPTNet/blob/465f96710c92e1fe407b80cc88c559411cf0395d/train_spt.py#L77
it already consumed the max memory of 3090, leading to the corruption. 
I did not change any code related to the training. Do you have any suggestion? Thank you very much!

**Comment by whj363636** [comment]
Hi @RunDevil-Run 

Not quite sure the reason. I've also executed the code on my server, carefully following the instructions provided in the repository, using the same RTX 3090Ti as you, and it performed successfully. Actually it only costs around 22G (see Figure 2). Is there any additional information you can provide to help me identify the problem?

![image](https://github.com/Visual-AI/SPTNet/assets/8454140/e8613976-90c8-4f6d-8025-823b5c19def0)
![image](https://github.com/Visual-AI/SPTNet/assets/8454140/8ce0824f-89b2-4ec1-9e7e-eade6b2f180d)

**Comment by RunDevil-Run** [comment]
fixed by updating torch to 1.13.1, thank you for your reply!
