### ISSUE TITLE
feasibility for general classification

### ISSUE THREAD

**Issue by syf-fgnb** [Visual-AI/SPTNet#14]
Hi,

Thanks for your excellent work and doc. Currently, I am actively involved in a GCD-related project, and your work is instrumental in reproducing the results. Based on my trials, SPTNet indeed shows contribution to the GCD task. However, I am curious to know if you have investigated the potential of utilizing the alternative method for enhancing representation in broader classification tasks, such as Flowers-102. Have you conducted any experiments in this context?

**Comment by whj363636** [comment]
Hi @syf-fgnb 

Thanks for your interest. SPTNet's ability to enhance representation indicates its potential in general classification tasks. We have indeed conducted relevant experiments and achieved performance that is comparable to VPT. However, it's worth noting that we did not incorporate contrastive learning, which, as demonstrated in our ablation study, plays a more significant role in the GCD task. Additionally, the performance in general classification can be further improved by considering factors such as hyperparameter tuning, as extensive parameter exploration was not conducted in this particular task.
