### ISSUE TITLE
About abstract description

### ISSUE THREAD

**Issue by wendy26zhang** [Visual-AI/SPTNet#17]
I would like to ask which SOTA method is that "Notably, we find our method achieves an average accuracy of 61.4% on the SSB, surpassing prior state-of-the-art methods by approximately **10%**." in abstract. Looking forward to your reply.

**Comment by whj363636** [comment]
Hi @wei26zhang 

Thanks for the interest. The SoTA method we referred to at that time is SimGCD

**Comment by wendy26zhang** [comment]
Thanks for your reply. However, i cannot find the margin(10%) between SimGCD (56.1%) vs SPTNet (61.4%) in Table 4. Do i miss something in paper?

**Comment by whj363636** [comment]
There may be some ambiguity that could lead to confusion. The number mentioned in the abstract represents an average _proportional_ improvement. For further details, please see the "Evaluation on Fine-Grained Datasets" paragraph, where we state, "achieving an average absolute improvement of approximately 5% and an average proportional improvement of approximately 10% across all evaluated datasets in SSB."

**Comment by wendy26zhang** [comment]
Oh I see! Could you tell me how to calculate the average proportional improvement on SSB dataset? Thanks again!

**Comment by whj363636** [comment]
Just compute the improvement for each dataset and average them.
