### ISSUE TITLE
About unfreeze and freeze function.

### ISSUE THREAD

**Issue by ChMingLee** [Visual-AI/SPTNet#2]
Thank for your code.
"
from util.general_utils import str2bool, get_params_groups, finetune_params, freeze, unfreeze, cosine_lr
"
I can't find codes about 'freeze' and 'unfreeze'.
Meanwhile, pretrained vit can't be loaded on classifier.
"
    projector = DINOHead(in_dim=args.feat_dim, out_dim=args.num_ctgs, nlayers=args.num_mlp_layers)
    classifier = nn.Sequential(backbone, projector).cuda()
    state_dict = torch.load(args.pretrained_model_path, map_location='cpu')
    classifier.load_state_dict(state_dict)
"
Maybe classifier.load_state_dict(state_dict, strict = False) or backbone.load_state_dict(state_dict).

**Comment by whj363636** [comment]
Hi @ChMingLee

For the 'freeze' and 'unfreeze' function, please see the latest version of code. As for the snippet you provide, it is located in train_spt.py, meaning it is the model provided by your own. If you would like to evaluate our pretrained model, please run 'eval.py' file in the command line.
